"""Add images_enabled column

Revision ID: a87572b9ee6c
Revises: accd4ead82d2
Create Date: 2026-03-25 20:08:19.635461

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a87572b9ee6c'
down_revision: Union[str, None] = 'accd4ead82d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dbuser', sa.Column('images_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dbuser', 'images_enabled')
    # ### end Alembic commands ###
